name: CAS Frontend CI

on:
  push:
    branches: [ "main", "develop", "release" ]
  pull_request:
    branches: [ "main", "develop", "release" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Repo code checkout
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Dependencies installation
        run: npm ci

      - name: Tests execution
        run: npx vitest run